data_base_lh={'/home/pierre/temp/graph/Thickness/ajos/surf/lh.thickness',...
'/home/pierre/temp/graph/Thickness/betty/surf/lh.thickness',...
'/home/pierre/temp/graph/Thickness/bonnet/surf/lh.thickness',...
'/home/pierre/temp/graph/Thickness/gantheil/surf/lh.thickness',...
'/home/pierre/temp/graph/Thickness/gauin/surf/lh.thickness'};

% Discarded '/home/pierre/temp/graph/Thickness/artus/surf/lh.thickness'
% '/home/pierre/temp/graph/Thickness/bedin/surf/lh.thickness',...
% '/home/pierre/temp/graph/Thickness/belikov/surf/lh.thickness',...

spheres_lh={'/home/pierre/temp/graph/Thickness/ajos/surf/lh.sphere.reg',...
'/home/pierre/temp/graph/Thickness/betty/surf/lh.sphere.reg',...
'/home/pierre/temp/graph/Thickness/bonnet/surf/lh.sphere.reg',...
'/home/pierre/temp/graph/Thickness/gantheil/surf/lh.sphere.reg',...
'/home/pierre/temp/graph/Thickness/gauin/surf/lh.sphere.reg'};

% Discarded '/home/pierre/temp/graph/Thickness/artus/surf/lh.sphere.reg'
% '/home/pierre/temp/graph/Thickness/bedin/surf/lh.sphere.reg',...
% '/home/pierre/temp/graph/Thickness/belikov/surf/lh.sphere.reg',...


N = size(data_base_lh, 2);

for i = 1 : N
    fprintf('%s\n%s\n', char(spheres_lh{i}), char(data_base_lh{i}));
    XX = vert_to_mat(char(spheres_lh{i}), char(data_base_lh{i}), 'corr');
    L = size(XX, 1)/2;
    [G,H] = swp_genfilters(5, L, 3);
    WW = swp(XX, G, H, 3);
    Field = strcat('subj', int2str(i));
    eval(strcat('Mat.', Field, '=', mat2str(XX), ';'));
    eval(strcat('App.', Field, '=', mat2str(WW.app), ';'));
end

clear XX WW;