function Mat = weight_connect_coeff(Mat_in, StatsPath, Dist)
% usage : MAT = weight_connect_coeff(MAT_IN, STATS_PATH, DIST)
%
% INPUT :
% -------
%    MAT_IN            : Uncorrected connectivity matrix
%
%    STATS_PATH        : Path to stats file generated by the function
%       mris_anatomical_stats
%
%    DIST              : Distance matrix
%
% OUTPUT :
% --------
%    MAT               : Corrected connectivity matrix
%
% Pierre Besson, August 2009

if nargin ~= 3
    error('Incorrect usage');
end

if size(Dist, 1) ~= size(Mat_in, 1)
    error('Size of DIST and MAT_IN should be the same');
end

% Read Stats file
Stats = textread(StatsPath, '%s', 'commentstyle', 'shell');
Stats = reshape(Stats, 10, length(Stats) ./ 10);
Stats = Stats(3, :);
Stats = str2num(char(Stats));

% Remove diagnal elements
Mat_in = Mat_in .* (ones(size(Mat_in)) - eye(size(Mat_in)));
Mat = zeros(size(Mat_in));

% Weigh the matrix (not fast but it works)
for i = 2 : size(Mat_in, 1)
    for j = 1 : i-1
        % Dist = sqrt( (Coord(j,1)-Coord(i,1)).^2 + (Coord(j,2)-Coord(i,2)).^2 + (Coord(j,3)-Coord(i,3)).^2 );
        if Dist(i,j) ~= 0
            Mat(i,j) = 2 .* Mat_in(i,j) ./ ((Stats(i) + Stats(j)) .* Dist(i,j));
            Mat(j,i) = Mat(i,j);
        else
            Mat(i,j) = 0;
            Mat(j,i) = 0;
        end
    end
end