#!/bin/bash

if [ $# -lt 1 ]
then
	echo "Usage: local-recon-all arguments"
	echo ""
	echo "Arguments following local-recon-all are exactly those following the classical recon-all"
	echo ""
	echo "qcache step is automatically processed"
	echo ""
	echo "Usage: local-recon-all arguments"
	exit 1
fi

CL=""
index=1
while [ $index -le $# ]
do
	eval arg=\${$index}
	case "$arg" in
	-all|-autore*)
		eval ACTION=\${$index}
		;;
	-sd)
		SD=`expr $index + 1`
		eval SD=\${$SD}
		index=$[$index+1]
		;;
	-subjid|-sid)
		SID=`expr $index + 1`
		eval SID=\${$SID}
		index=$[$index+1]
		;;
	-i)
		INPUT=`expr $index + 1`
		eval INPUT=\${$INPUT}
		index=$[$index+1]
		;;
	*)
		T=`expr $index`
		eval T=\${$T}
		CL="${CL} ${T}"
		;;
	esac
	index=$[$index+1]
done

# Launch recon-all locally
# echo ${CL}
# echo action = ${ACTION}
# echo subjid = ${SID}
# echo sd     = ${SD}
# echo input  = ${INPUT}

# Initialisation before recon-all cmd
# init_fs5.1
export FREESURFER_HOME=/home/global/freesurfer5.1/
. ${FREESURFER_HOME}/SetUpFreeSurfer.sh
recon-all ${ACTION} -sd /tmp/ -subjid ${SID} ${CL} -no-isrunning -i ${INPUT}

# recon-all -qcache -sd /tmp/ -subjid ${SID} ${CL} -no-isrunning # corrected qcache command because of some rights troubles with fsaverage link

cp -R /tmp/${SID} ${SD}/

recon-all -qcache -sd ${SD} -subjid ${SID} ${CL} -no-isrunning
