function  global_lesion= lesional_tissue(init)
% 
% lesional_tissue compute lesional tissue matrix
% 
% usage :  global_lesion= lesional_tissue(init)
% 
% INPUTS :
%       init : initialization structure - generated by initvar.m and
%       generate_variables.m
%
% OUTPUTS : 
%       global_lesion : lesional tissue matrix
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012



%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012


global_lesion = zeros(init.size,0);

 
 for i = 1 : length(init.train)
                
        for m = 1 : 8
            lh_list{m,1} = strcat(init.pat_SD,init.train{i},'/epilepsy/lh.fwhm',num2str(init.FWHM),'.zscore.fsaverage.',init.features{m});
        end
        for m = 1 : 2
            lh_list{m+8,1} = strcat(init.pat_SD,init.train{i},'/epilepsy/lh.fwhm',num2str(init.FWHM),'.flair_nuc.zscore.fsaverage.',init.features_flair{m});
        end
                
        lh_patient_lesion = SurfStatReadData(lh_list);
        
        for m = 1 : 8
            rh_list{m,1} = strcat(init.pat_SD,init.train{i},'/epilepsy/rh.fwhm',num2str(init.FWHM),'.zscore.fsaverage.',init.features{m});
        end
        for m = 1 : 2
            rh_list{m+8,1} = strcat(init.pat_SD,init.train{i},'/epilepsy/rh.fwhm',num2str(init.FWHM),'.flair_nuc.zscore.fsaverage.',init.features_flair{m});
        end
        
        rh_patient_lesion = SurfStatReadData(rh_list);
        
        
        lh_lesion = SurfStatReadData(strcat(init.lab_SD,init.train{i},'/','lh.fwhm5.fsaverage.lesion.mgh'));
        rh_lesion = SurfStatReadData(strcat(init.lab_SD,init.train{i},'/','rh.fwhm5.fsaverage.lesion.mgh'));
        
        rh_patient_lesion(:,rh_lesion==0)=[];
        lh_patient_lesion(:,lh_lesion==0)=[];
        
        disp(strcat('lh_lesion : ',num2str(size(lh_patient_lesion,2)),'  lesional vertex'))
        disp(strcat('rh_lesion : ',num2str(size(rh_patient_lesion,2)),'  lesional vertex'))
        
        global_lesion = [global_lesion lh_patient_lesion];
        global_lesion = [global_lesion rh_patient_lesion];
        
        
 end
 
 
 disp(strcat('total ',num2str(size(global_lesion,2)),'  lesional vertex'))