function global_control = non_lesional_tissue(init)
% 
% non_lesional_tissue compute healthy tissue matrix
% 
% usage :  global_lesion= non_lesional_tissue(init)
% 
% INPUTS :
%       init : initialization structure - generated by initvar.m and
%       generate_variables.m
%
% OUTPUTS : 
%       global_control : healthy tissue matrix
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012



%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012



%%% global_lh_control

global_lh_control=[];
for m = 1 : length(init.features)
    
    List_Controle = arrayfun(@(i) strcat( init.cont_SD,i,'/epilepsy/lh.fwhm',num2str(init.FWHM),'.zscore.fsaverage.',init.features{m}),init.cont)';
    
    lh_control = SurfStatReadData(List_Controle);    
    lh_control(:,init.lh_mask==1)=[];
    
    global_lh_control = [global_lh_control ; reshape(lh_control',1,numel(lh_control))];
    
end

clear List_Controle lh_control

for m = 1 : length(init.features_flair)
    
    List_Controle = arrayfun(@(i) strcat( init.cont_SD,i,'/epilepsy/lh.fwhm',num2str(init.FWHM),'.flair_nuc.zscore.fsaverage.',init.features_flair{m}),init.cont)';
    
    lh_control = SurfStatReadData(List_Controle);
    lh_control(:,init.lh_mask==1)=[];
    
    global_lh_control = [global_lh_control ; reshape(lh_control',1,numel(lh_control))];
    
end


%%% global_rh_control

global_rh_control=[];
for m = 1 : length(init.features)
    
    List_Controle = arrayfun(@(i) strcat( init.cont_SD,i,'/epilepsy/rh.fwhm',num2str(init.FWHM),'.zscore.fsaverage.',init.features{m}),init.cont)';
    
    rh_control = SurfStatReadData(List_Controle);    
    rh_control(:,init.rh_mask==1)=[];
    
    global_rh_control = [global_rh_control ; reshape(rh_control',1,numel(rh_control))];
    
end

clear List_Controle rh_control

for m = 1 : length(init.features_flair)
    
    List_Controle = arrayfun(@(i) strcat( init.cont_SD,i,'/epilepsy/rh.fwhm',num2str(init.FWHM),'.flair_nuc.zscore.fsaverage.',init.features_flair{m}),init.cont)';
    
    rh_control = SurfStatReadData(List_Controle);
    rh_control(:,init.rh_mask==1)=[];
    
    global_rh_control = [global_rh_control ; reshape(rh_control',1,numel(rh_control))];
    
end


%%% global_control

global_control = [global_lh_control global_rh_control];
