num_cores_per_subject: 4

num_subjects_at_once: 1

output_directory: /NAS/dumbo/protocoles/strokconnect/QA

working_directory: /NAS/dumbo/protocoles/strokconnect/QAtmp

write_all_outputs: False

start_idx: 0

stop_idx: None

slice_timing_correction: True

template_brain_for_anat: /home/global/fsl50/data/standard/MNI152_T1_2mm_brain.nii.gz

template_skull_for_anat: /home/global/fsl50/data/standard/MNI152_T1_2mm.nii.gz

write_report: True

write_graph: True
