Pt_maps=char('/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject001_Condition001_Source003.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject002_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject003_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject004_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject005_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject006_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject007_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject008_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject009_Condition001_Source002.nii');

T_maps=char('/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject010_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject011_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject012_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject013_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject014_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject015_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject016_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject017_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject018_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject019_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject020_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject021_Condition001_Source002.nii',...
'/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/firstlevel/ANALYSIS_01/BETA_Subject022_Condition001_Source002.nii');
       

%coord mni IRM 39/-51/46 
%donc coord freesurfer (matrice) 26/38/59
%donc +1 pour matlab 27/39/60
x=27;
y=39;
z=60;

for cpt=1:1:size(Pt_maps,1)
    Pt = spm_vol(Pt_maps(cpt,:));
    Pt_vals = spm_read_vols(Pt);
    Patients(cpt,1)=Pt_vals(x,y,z);
end

for cpt=1:1:size(T_maps,1)
    Pt = spm_vol(T_maps(cpt,:));
    T_vals = spm_read_vols(Pt);
    Temoins(cpt,1)=T_vals(x,y,z);
end

Patients
Temoins

P = spm_vol('/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/secondlevel/ANALYSIS_01/p/rest/aIPS/spmT_0001.nii');
FA = spm_read_vols(P);
FA(x,y,z)
[h,p,ci,stats] = ttest(Patients)

P = spm_vol('/NAS/dumbo/protocoles/strokconnect/rs/results/conn_strokConnect14/results/secondlevel/ANALYSIS_01/t/rest/aIPS/spmT_0001.nii');
FA = spm_read_vols(P);
FA(x,y,z)
[h,p,ci,stats] = ttest(Temoins)

P = spm_vol('/NAS/dumbo/protocoles/strokconnect/rs/results//PatientsVsTemoins_aIPS/spmT_0001.nii');
FA = spm_read_vols(P);
FA(x,y,z)
%P = spm_vol('/NAS/dumbo/protocoles/strokconnect/rs/results/aIPS_twosamplesTTest/spmT_0002.nii');
[h,p,ci,stats] = ttest2(Patients,Temoins)
%p = anova_rm({Patients Temoins});
 
