FA_maps=char('/NAS/tupac/protocoles/alexcis/FS53/p_AR28/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_BB38/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_CD15/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_CN31/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_DG21/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_ED24/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_EH23/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_GM13/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_HB20/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_HB27/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_IA39/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_IC17/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_ID19/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_JB36/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_JN26/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_LG10/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_LL34/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_MG30/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_NC12/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_NR22/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_SG18/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_SL29/dti/wdti_finalcor_FA.nii', ...
'/NAS/tupac/protocoles/alexcis/FS53/p_VC4/dti/wdti_finalcor_FA.nii');

x=33;
y=61;
z=45;

for cpt=1:1:size(FA_maps,1)
    P = spm_vol(FA_maps(cpt,:));
    FA = spm_read_vols(P);
    NDG(cpt,1)=FA(x,y,z);
end

CUD_viusel=[-3.02;12.56;68.335;-8.4;171.52;114;83.22;-73.13;-91.75;-74.43;39.97;56.95;5.82;-48.86;119.53;-4.02;-87.69;48.5;38.63;-21.08;-25.84;-5.84;-42.73];


P = spm_vol('/NAS/tupac/protocoles/alexcis/resu/CUD_visuel/spmT_0001.nii');
FA = spm_read_vols(P);
FA(x,y,z);

[h,p] = ttest(NDG,CUD_viusel)

