function checkMovementParameters(mc_log, fig_path)
%
% usage : checkMovementParameters(MC_LOG, FIGURE_PATH)
%
% Display movement parameters found by linear registration
%
% Input :
%     MC_LOG       : log file generated by fmr_preprocess
%     FIGURE_PATH  : path to the mouvement figure
%
% Pierre Besson @ CHRU Lille, June 2011

if nargin ~= 2
    error('invalid usage');
end

try
    fid = fopen(mc_log, 'r');
catch
    error(['can not open ', mc_log]);
end

Parameters = readMCMotion(mc_log);
Parameters = Parameters(:, 1:end-1);

h=figure('visible', 'off');
plot(Parameters);
xlabel('Image number');
ylabel('Movement (degree or mm)');
legend('x translation', 'y translation', 'z translation', 'x rotation', 'y rotation', 'z rotation')
saveas(h, fig_path)