function motion = readMCMotion(mc_log)
%
% usage : MOTION = readMCMotion(MC_LOG)
%
% Read motions from a MC log file
%
% MOTION = [dx dy dz rx ry rz corr]
%   dx   : x translation
%   dy   : y translation
%   dz   : z translation
%   rx   : x rotation
%   ry   : y rotation
%   rz   : z rotation
%   corr : final correlation coefficient
%
% Input :
%     MC_LOG     : log file generated by fmr_preprocess
%
% Pierre Besson @ CHRU Lille, June 2011

if nargin ~= 1
    error('invalid usage');
end

try
    fid = fopen(mc_log, 'r');
catch
    error(['can not open ', mc_log]);
end

while 1
    tline = fgetl(fid);
    if ~isempty(regexpi(tline, 'dx'))
        break;
    end
end

motion = [];

while 1
    tline = fgetl(fid);
    if isempty(tline)
        break;
    else
        motion = [motion; char(tline)];
    end
end

motion = str2num(motion);