function results = mni_ANIMAL_DTI(lambdasFnameBase,animalFname)

% load /media/noel/noel2/luis/scripts/ANIMAL-labels.mat

labels  = readmnc(animalFname);

[lambdas,info] = load_lambdas_mnc(lambdasFnameBase);
lambdas = lambdas  .* 1000;
[maps.ADC,maps.FA,maps.PERP] = calcFA(lambdas);
maps.e1 = squeeze(lambdas(:,:,:,1));
maps.e2 = squeeze(lambdas(:,:,:,2));
maps.e3 = squeeze(lambdas(:,:,:,3));


ANIMAL = unique(labels);


results.meanValues = zeros(length(ANIMAL),8);
results.sdValues   = zeros(length(ANIMAL),8);
for lab = 1 : length(ANIMAL)
   index = find(labels==lab);
   results.meanValues(lab,:) = [ANIMAL(lab) ...
                        nanmean(maps.FA(index)) ...
                        nanmean(maps.ADC(index)) ...
                        nanmean(maps.e1(index)) ...
                        nanmean(maps.e2(index)) ...
                        nanmean(maps.e3(index)) ...
                        nanmean(maps.PERP(index)) ...
                        length(index)];
   results.sdValues(lab,:) = [ANIMAL(lab) ...
                        nanstd(maps.FA(index)) ...
                        nanstd(maps.ADC(index)) ...
                        nanstd(maps.e1(index)) ...
                        nanstd(maps.e2(index)) ...
                        nanstd(maps.e3(index)) ...
                        nanstd(maps.PERP(index)) ...
                        length(index)];
end



