%%
% 
% Initvar allows you to manage variables 
% for automatic classification of Focal Cortical Dysplasia
% 
% It generates a Matlab structure containing initial variables
% 
% It need to be used before each use of classification.
% 
% usage : initvar;
% 
% 
% Example of Output :
%
% init = 
% 
%           features: {'complexity'  'curv'  'depth'  'dxyz'  'intensity'  'jacobian'  'thickness'  'pet'}
%     features_flair: {'dxyz'  'intensity'}
%               blur: [5 10 15 20]
%                pat: {1x14 cell}
%             pat_SD: '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Patients/'
%               cont: {1x11 cell}
%            cont_SD: '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/'
%           temp_dir: '/home/tanguy/NAS/tanguy/CLASS_2013/TEMPLATES/'
%      fsaverage_dir: '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/fsaverage/'
%           mask_way: '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Mask/media_wall.mat'
%              nbles: 1000
%              nbhea: 2000
%                lab: {'BODAR'  'COBERAC'  'DELAVAL'  'KOCHIH'}
%             lab_SD: '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Labels/'
%              train: {'BODAR'  'COBERAC'  'DELAVAL'  'KOCHIH'}
%               FWHM: 5
%                val: {'BODAR'  'COBERAC'  'DELAVAL'  'KOCHIH'}
%             val_SD: '/home/tanguy/NAS/tanguy/CLASS_2013/VALIDATION/'
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012



%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012



%% FEATURES & BLUR

% init.features & init.features_flair : features used to characterize FCD
%
% init.blur : surface blur used
%
% WARNING : you need to have the files corresponding to this features and
% blur values.
% most of this files are generated by the script "Surface_features.sh" or
% "Surface_features_2.sh"
%
%
%
% Example : 
% init.features = {'complexity' 'curv' 'depth' 'dxyz' 'intensity' 'jacobian' 'thickness' 'pet'};
% 
% init.features_flair = {'dxyz' 'intensity'};
% 
% init.blur = [5 10 15 20];
% 

init.features = {'complexity' 'curv' 'depth' 'dxyz' 'intensity' 'jacobian' 'thickness' 'pet'};

init.features_flair = {'dxyz' 'intensity'};

init.blur = [5 10 15 20];

%% PATIENTS

% init.pat : List of patients names. It need to contain patients of
% training and validation sets.
%
% init.pat_SD : Subjects_Dir : folder containing patient folders.
%
%
%
% Example : 
% init.pat = {'BODAR' 'COBERAC' 'DANIEAU' 'DELAVAL' 'DRUENNE' 'FOUCHER' 'FROBERT' 'KOCHIH' 'LEBRETO' 'MOLLET' 'PARCINSKI' 'PENDELI' 'PICART' 'SOUFFLET'};
% init.pat_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Patients/';


init.pat = {'BODAR' 'COBERAC' 'DANIEAU' 'DELAVAL' 'DRUENNE' 'FOUCHER' 'FROBERT' 'KOCHIH' 'LEBRETO' 'MOLLET' 'PARCINSKI' 'PENDELI' 'PICART' 'SOUFFLET'};
init.pat_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Patients/';


%% CONTROL

% init.cont : List of control names.
%
% init.cont_SD : Subjects_Dir : folder containing control folders.
%
%
%
% Example :
% init.cont = {'BILLORE' 'BRASSART' 'CAFFIER' 'DEHAES' 'DELATTRE' 'DEULIN' 'DIDI' 'FIEMS' 'LANNOY' 'PRUDHOM' 'TRIGEAU'};
% init.cont_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/';


init.cont = {'BILLORE' 'BRASSART' 'CAFFIER' 'DEHAES' 'DELATTRE' 'DEULIN' 'DIDI' 'FIEMS' 'LANNOY' 'PRUDHOM' 'TRIGEAU'};
init.cont_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/';



%% TEMPLATES

% init.temp_dir : folder where the template data will be placed and read
%
% Example : 
% init.temp_dir = '/home/tanguy/NAS/tanguy/CLASS_2013/TEMPLATES/';


init.temp_dir = '/home/tanguy/NAS/tanguy/CLASS_2013/TEMPLATES/';


%% SURFACE & MASK

% init.fsaverage_dir : freesurfer_average : folder to read the surface
% template
%
% init.mask_way : way to find the mask data. Must be a .mat file.
% if you don't want to use a mask, put init.mask_way = '' ; 
%
% Example : 
% init.fsaverage_dir = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/fsaverage/';
% init.mask_way = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Mask/media_wall.mat';


init.fsaverage_dir = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Control/fsaverage/';
init.mask_way = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Mask/media_wall.mat';


%% LESION

% Informations about lesion data (patients and number of vertex for classification)
%
% init.nbles : number of lesional vertex for classification
% init.nbhea : number of healthy vertex for classification
%
% init.lab : list of patients who were labels
% init.lab_SD : folder containing label files
%
%
% Example :
% init.nbles = 1000;
% init.nbhea = 2000;
% 
% init.lab = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};
% init.lab_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Labels/';


init.nbles = 1000;
init.nbhea = 2000;

init.lab = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};
init.lab_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/DATA/Labels/';


%% TRAINING

% Informations about training set 
%
% init.train : patients for training set
% WARNING : you must have patients files into init.pat_SD and label into
% init.lab_SD for each of them
%
% init.FWHM : blur used for lesional vertex
%
%
% Example :
% init.train = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};
% 
% init.FWHM = 5;
% can't be equal 0

init.train = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};

init.FWHM = 5;

%% VALIDATION

% Informations about validation set 
%
% init.val : patients for validation set
% WARNING : you must have patients files into init.pat_SD and label into
% init.lab_SD for each of them
%
% init.val_SD : folder to reccord classified data
%
% Example :
% init.val = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};
% 
% init.val_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/VALIDATION/'


init.val = {'BODAR' 'COBERAC' 'DELAVAL' 'KOCHIH'};

init.val_SD = '/home/tanguy/NAS/tanguy/CLASS_2013/VALIDATION/'

%% CLASSIFIERS

% Quantity of each classifier
%
% init.nbnn : number of neural networks
% init.nbdt : number of decision trees
% init.nbsvm : number of iteration of SVM
%
%
% Example :
% 
% init.nbnn = 200;
% init.nbdt = 500;
% init.nbsvm = 100;


init.nbnn = 200;
init.nbdt = 500;
init.nbsvm = 100;
