function normalizefs(init)
%
%
%
% normalize data for patients in FS
%
%
% usage : normalizefs(init)
%
% Inputs :
%       init : structure generated by initvar.m and generate_variables.m
%              patient list and other variables must be changed into these
%              scripts.
%
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012


%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012
%%


for pat = init.pat

    normalizepatient(init, pat{1})
    
end

