function normalizepatient(init,pat)
%
%
%
% normalize data for patients pat
%
%
% usage : normalizepatient(init,pat)
%
% Inputs :
%       init : structure generated by initvar.m and generate_variables.m
%              patient list and other variables must be changed into these
%              scripts.
%       pat : name of patient or controle to normalize
%
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012


%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012
%%



%Normalisation of T1 & PET

for k=1:size(init.features,2)
    
    %Normalization of not blured data
    
    temp_left = SurfStatReadData(strcat(init.temp_dir,'/normalization/lh.temp.fsaverage.',init.features{k}));
    temp_right = SurfStatReadData(strcat(init.temp_dir,'/normalization/rh.temp.fsaverage.',init.features{k}));
    
    F_left = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.fsaverage.',init.features{k},'.mgh'));
    F_right = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.fsaverage.',init.features{k},'.mgh'));
    
    [F_left_norm , F_right_norm] = norma(F_left, F_right, temp_left, temp_right);
    
    SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.norm.fsaverage.',init.features{k}),F_left_norm,'b');
    SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.norm.fsaverage.',init.features{k}),F_right_norm,'b');
    
    %Normalization for blur (blur values can be managed with initvar.m)
    
    
    for i = init.blur
        
        temp_left = SurfStatReadData(strcat(init.temp_dir,'/normalization/lh.fwhm',num2str(i),'.temp.fsaverage.',init.features{k}));
        temp_right = SurfStatReadData(strcat(init.temp_dir,'/normalization/rh.fwhm',num2str(i),'.temp.fsaverage.',init.features{k}));
        
        F_left = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.fwhm',num2str(i),'.fsaverage.',init.features{k},'.mgh'));
        F_right = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.fwhm',num2str(i),'.fsaverage.',init.features{k},'.mgh'));
        
        [F_left_norm , F_right_norm] = norma(F_left, F_right, temp_left, temp_right);
        
        SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.fwhm',num2str(i),'.norm.fsaverage.',init.features{k}),F_left_norm,'b');
        SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.fwhm',num2str(i),'.norm.fsaverage.',init.features{k}),F_right_norm,'b');
        
        
    end
    
end


%Normalisation of FLAIR

for k=1:size(init.features_flair,2)
    
    %Normalization of not blured data
    
    temp_left = SurfStatReadData(strcat(init.temp_dir,'/normalization/lh.flair_nuc.temp.fsaverage.',init.features_flair{k}));
    temp_right = SurfStatReadData(strcat(init.temp_dir,'/normalization/rh.flair_nuc.temp.fsaverage.',init.features_flair{k}));
    
    F_left = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.flair_nuc.fsaverage.',init.features_flair{k},'.mgh'));
    F_right = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.flair_nuc.fsaverage.',init.features_flair{k},'.mgh'));
    
    [F_left_norm , F_right_norm] = norma(F_left, F_right, temp_left, temp_right);
    
    SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.flair_nuc.norm.fsaverage.',init.features_flair{k}),F_left_norm,'b');
    SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.flair_nuc.norm.fsaverage.',init.features_flair{k}),F_right_norm,'b');
    
    %Normalization for blur (blur values can be managed with initvar.m)
    
    
    for i = init.blur
        
        temp_left = SurfStatReadData(strcat(init.temp_dir,'/normalization/lh.fwhm',num2str(i),'.flair_nuc.temp.fsaverage.',init.features_flair{k}));
        temp_right = SurfStatReadData(strcat(init.temp_dir,'/normalization/rh.fwhm',num2str(i),'.flair_nuc.temp.fsaverage.',init.features_flair{k}));
        
        F_left = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.fwhm',num2str(i),'.flair_nuc.fsaverage.',init.features_flair{k},'.mgh'));
        F_right = SurfStatReadData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.fwhm',num2str(i),'.flair_nuc.fsaverage.',init.features_flair{k},'.mgh'));
        
        [F_left_norm , F_right_norm] = norma(F_left, F_right, temp_left, temp_right);
        
        SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/lh.fwhm',num2str(i),'.flair_nuc.norm.fsaverage.',init.features_flair{k}),F_left_norm,'b');
        SurfStatWriteData(strcat(init.pat_SD,'/',pat,'/epilepsy/rh.fwhm',num2str(i),'.flair_nuc.norm.fsaverage.',init.features_flair{k}),F_right_norm,'b');
        
        
    end
    
end





