function verif_ok = verif(init)


%
%
% verification function
%
%
% Checks the existe of necessary files into the patients and controls folders 
%
% Makes other verifications
%
% usage : verif_ok = verif(init)
%
% INPUTS :
%       init : structure generated by initvar.m and generate_variables.m
%              patient list and other variables must be changed into these
%              scripts.
%
% OUTPUTS :
%       verif_ok : boolean (0 or 1). 1 if all is ok.
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012


%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012
%%

verif_ok=1;


%% Données de controle




list = {};
for name = init.cont
    
    for blur = init.blur
        
        list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/lh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
        list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/rh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
        
        list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/lh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
        list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/rh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
        
    end
    
    list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/lh.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
    list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/rh.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
    
    list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/lh.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
    list = [list ; arrayfun(@(feat) strcat(init.cont_SD,name,'/epilepsy/rh.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
end



ex = cell2mat(arrayfun(@(l) exist(l{1}{1}), list,'UniformOutput',false));

tot = sum(ex==0);

if tot~=0
    disp('problem with control files');
    disp(' ');
    disp(strcat('missing files : ',num2str(tot)));
    for i = 1 : length(list)
        if ex(i)==0
            disp(list{i}{1});
        end
    end
    verif_ok = 0;
    
else
    disp('control files ok');
end


clear list ex

%% Données patients

list = {};

for name = init.pat
    
    for blur = init.blur
        
        list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/lh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
        list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/rh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
        
        list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/lh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
        list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/rh.fwhm',num2str(blur),'.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
        
    end
    
    list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/lh.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
    list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/rh.fsaverage.',feat,'.mgh'),init.features,'UniformOutput',false)'];
    
    list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/lh.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
    list = [list ; arrayfun(@(feat) strcat(init.pat_SD,name,'/epilepsy/rh.fsaverage.',feat,'.mgh'),init.features_flair,'UniformOutput',false)'];
end





ex = cell2mat(arrayfun(@(l) exist(l{1}{1}), list,'UniformOutput',false));

tot = sum(ex==0);

if tot~=0
    disp('problem with patients files');
    disp(' ');
    disp(strcat('missing files : ',num2str(tot)));
    for i = 1 : length(list)
        if ex(i)==0
            disp(list{i}{1});
        end
    end
    verif_ok = 0;
    
else
    disp('patients files ok');
end




%% vérification de la présence des labels pour les jeu d'entrainement et de validation

if ~all(cellfun(@(name) ~all(strcmp(init.lab,name)==0),init.train))
    warning('all the train set need to be into init.lab')
    warning('init.lab contains all the labels')
    warning('you need label for training set ')
    verif_ok = 0;
end

if ~all(cellfun(@(name) ~all(strcmp(init.lab,name)==0),init.val))
    warning('all the validation set need to be into init.lab')
    warning('init.lab contains all the labels')
    warning('you need label for validation set')
    verif_ok = 0;
end

if (length(init.val) + length(init.train)) < length(init.lab)
    warning('some labels will not be used')
end


