function zscoretemplate(init)

%
%
%
% compute the zscore template from control data
%
%
% usage : zscoretemplate(init)
%
% Inputs :
%       init : structure generated by initvar.m and generate_variables.m
%              patient list and other variables must be changed into these
%              scripts.
%
%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012


%%
% For Automatic Detection of Focal Cortical Dysplasia
% Tanguy Hamel @ CHRU Lille, 2012

%% zscore for T1 & pet

for k=1:size(init.features,2)
    
    % zscore of not blured data
      
    List_lh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/lh.norm.fsaverage.' , init.features{k} ),init.cont)';
    List_rh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/rh.norm.fsaverage.' , init.features{k} ),init.cont)';
    
    if all(cellfun(@(i) exist(i),List_lh)~=0) && all(cellfun(@(i) exist(i),List_rh)~=0)
        F_left = SurfStatReadData(List_lh);
        F_right = SurfStatReadData(List_rh);
    else
        warning(strcat('problem in the control file for',init.features{k}, '& blur = 0 '))
        return
    end
        
    Meanlh = mean(F_left, 1);
    Meanrh = mean(F_right, 1);
    Stdlh = std(F_left, 1);
    Stdrh = std(F_right, 1);
    
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.mean.fsaverage.',init.features{k}),Meanlh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.mean.fsaverage.',init.features{k}),Meanrh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.std.fsaverage.',init.features{k}),Stdlh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.std.fsaverage.',init.features{k}),Stdrh,'b');
    
    clear L R List_lh List_rh F_left F_right
    
    %zscore for blur 5 - 10 - 15 - 20
        
    for blur = init.blur
                
        List_lh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/lh.fwhm',num2str(blur),'.norm.fsaverage.' , init.features{k}  ),init.cont)';
        List_rh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/rh.fwhm',num2str(blur),'.norm.fsaverage.' , init.features{k}  ),init.cont)';
        
        if all(cellfun(@(i) exist(i),List_lh)~=0) && all(cellfun(@(i) exist(i),List_rh)~=0)
            F_left = SurfStatReadData(List_lh);
            F_right = SurfStatReadData(List_rh);
        else
        warning(strcat('problem in the control file for',init.features{k}, '& blur =  ', num2str(blur)))
        end
                       
        Meanlh = mean(F_left, 1);
        Meanrh = mean(F_right, 1);
        Stdlh = std(F_left, 1);
        Stdrh = std(F_right, 1);
        
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.fwhm',num2str(blur),'.mean.fsaverage.',init.features{k}),Meanlh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.fwhm',num2str(blur),'.mean.fsaverage.',init.features{k}),Meanrh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.fwhm',num2str(blur),'.std.fsaverage.',init.features{k}),Stdlh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.fwhm',num2str(blur),'.std.fsaverage.',init.features{k}),Stdrh,'b');
        
        clear L R List_lh List_rh F_left F_right
        
    end
    
end


%% zscore for FLAIR

for k=1:size(init.features_flair,2)
    
    % zscore of not blured data
        
    List_lh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/lh.norm.fsaverage.' , init.features_flair{k}  ),init.cont)';
    List_rh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/rh.norm.fsaverage.' , init.features_flair{k}  ),init.cont)';
    
    if all(cellfun(@(i) exist(i),List_lh)~=0) && all(cellfun(@(i) exist(i),List_rh)~=0)
        F_left = SurfStatReadData(List_lh);
        F_right = SurfStatReadData(List_rh);
    else
        warning(strcat('problem in the control file for',init.features_flair{k}, '& blur = 0 '))
    end
        
    Meanlh = mean(F_left, 1);
    Meanrh = mean(F_right, 1);
    Stdlh = std(F_left, 1);
    Stdrh = std(F_right, 1);
    
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.flair_nuc.mean.fsaverage.',init.features_flair{k}),Meanlh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.flair_nuc.mean.fsaverage.',init.features_flair{k}),Meanrh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.flair_nuc.std.fsaverage.',init.features_flair{k}),Stdlh,'b');
    SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.flair_nuc.std.fsaverage.',init.features_flair{k}),Stdrh,'b');
    
    clear L R List_lh List_rh F_left F_right
        
    % zscore for blur 5 - 10 - 15 - 20
        
    for blur = init.blur
        
        List_lh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/lh.fwhm',num2str(blur),'.norm.fsaverage.' , init.features_flair{k}  ),init.cont)';
        List_rh = arrayfun(@(i) strcat(init.cont_SD , '/' , i , '/epilepsy/rh.fwhm',num2str(blur),'.norm.fsaverage.' , init.features_flair{k}  ),init.cont)';
        
        if all(cellfun(@(i) exist(i),List_lh)~=0) && all(cellfun(@(i) exist(i),List_rh)~=0)
            F_left = SurfStatReadData(List_lh);
            F_right = SurfStatReadData(List_rh);
        else
        warning(strcat('problem in the control file for',init.features_flair{k}, '& blur =  ',num2str(blur)))

        end
        
        Meanlh = mean(F_left, 1);
        Meanrh = mean(F_right, 1);
        Stdlh = std(F_left, 1);
        Stdrh = std(F_right, 1);
        
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.fwhm',num2str(blur),'.flair_nuc.mean.fsaverage.',init.features_flair{k}),Meanlh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.fwhm',num2str(blur),'.flair_nuc.mean.fsaverage.',init.features_flair{k}),Meanrh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/lh.fwhm',num2str(blur),'.flair_nuc.std.fsaverage.',init.features_flair{k}),Stdlh,'b');
        SurfStatWriteData(strcat(init.temp_dir,'/zscore/rh.fwhm',num2str(blur),'.flair_nuc.std.fsaverage.',init.features_flair{k}),Stdrh,'b');
        
        clear L R List_lh List_rh F_left F_right
        
    end
    
end

