Controls={'ajos', 'artus', 'bargoin3d', 'barret', 'bedin', 'belikov', 'berger3danat', 'betty', 'bonnet', 'brauR', 'brunet', 'gantheil', 'gauin', 'gauthier', 'jumarie', 'latu', 'michel', 'place', 'poirier', 'pradat', 'renac', 'rousseau', 'safar', 'seassau', 'servant', 'silnicki', 'tav', 'teskrat', 'varona', 'vol_fl'};
Controls_age = [22, 55, 24, 56, 49, 63, 29, 37, 48, 63, 59, 59, 46, 39, 59, 58, 24, 56, 46, 38, 38, 63, 39, 22, 53, 60, 45, 40, 60, 40];
Controls_path='/home/pierre/DataDisk/Thickness/Controls';

% Controls={'ajos', 'artus', 'barret', 'bedin', 'belikov', 'betty', 'bonnet', 'brauR', 'brunet', 'gantheil', 'gauin', 'gauthier', 'jumarie', 'latu', 'michel', 'place', 'poirier', 'pradat', 'renac', 'rousseau', 'safar', 'seassau', 'servant', 'silnicki', 'tav', 'teskrat', 'varona', 'vol_fl'};
% Controls_age = [22, 55, 56, 49, 63, 37, 48, 63, 59, 59, 46, 39, 59, 58, 24, 56, 46, 38, 38, 63, 39, 22, 53, 60, 45, 40, 60, 40];

Patients={'begon', 'benadiba_MEG', 'bequarMEG', 'berto3dMEG', 'biarne_MEG', 'bodeur', 'brunet', 'damienMEG', 'debotte', 'doliveira', 'egea', 'elkmy3d', 'giroux', 'jeananat3d', 'jolibois', 'leger', 'manicord', 'marchand', 'mari', 'pivette', 'rougeyron', 'senet', 'sm', 'td', 'zanon'};
Patients_age=[21, 62, 20, 41, 24, 59, 58, 31, 60, 39, 60, 50, 75, 45, 44, 51, 45, 50, 24, 50, 49, 52, 46, 43, 57];
Patients_path='/home/pierre/DataDisk/Thickness/Patients';

% Patients={'begon', 'bodeur', 'debotte', 'doliveira', 'egea', 'giroux', 'jeananat3d', 'jolibois', 'leger', 'manicord', 'marchand', 'mari', 'pivette', 'rougeyron', 'senet', 'sm', 'td', 'zanon'};
% Patients_age=[21, 59, 60, 39, 60, 75, 45, 44, 51, 45, 50, 24, 50, 49, 52, 46, 43, 57];

% Areas = {'unknown', ...
%     'bankssts', ...
%     'caudalanteriorcingulate', ...
%     'caudalmiddlefrontal',...
%     'corpuscallosum',...
%     'cuneus',...
%     'enthorhinal', ...
%     'fusiform',...
%     'inferiorparietal',...
%     'inferiortemporal',...
%     'isthmuscingulate',...
%     'lateraloccipital',...
%     'lateralorbitofrontal',...
%     'lingual',...
%     'medialorbitofrontal',...
%     'middletemporal',...
%     'parahippocampal',...
%     'paracentral',...
%     'parsopercularis',...
%     'parsorbitalis',...
%     'parstriangularis',...
%     'pericalcarine',...
%     'postcentral',...
%     'posteriorcingulate',...
%     'precentral',...
%     'precuneus',...
%     'rostralanteriorcingulate',...
%     'rostralmiddlefrontal',...
%     'superiorfrontal',...
%     'superiorparietal',...
%     'superiortemporal',...
%     'supramarginal',...
%     'frontalpole',...
%     'temporalpole',...
%     'transversetemporal'};

Areas = {'1';'2';'3';'4';'5';'6';'7';'8';'9';'10';'11';'12';'13';'14';'15';'16';'17';'18';'19';'20';'21';'22';'23';'24';'25';'26';'27';'28';'29';'30';'31';'32';'33';'34';'35'};
